import { Down1 } from "../src/icons/Down1";
import { Header } from "./components/Header";

import "./App.css";
import { LeftContainer } from "./components/LeftContainer/LeftContainer";
import bg_svg from "../src/assets/rightContainerImages/1.png";
import svg_1 from "../src/assets/rightContainerImages/2.svg";
import vector_4 from "../src/assets/rightContainerImages/vector_4.svg";

function App() {
  return (
    <>
      <div className="desktop">
        <div className="group-wrapper">
          <div className="group">
            <div className="overlap">
              <div className="div">
                <div className="overlap-group">
                  <img
                    className="clip-path-group"
                    alt="Clip path group"
                    src={bg_svg}
                  />
                  <img className="vector" alt="Vector" src={svg_1} />
                  <img
                    className="img"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-2.svg"
                  />
                  <img
                    className="vector-2"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-3.svg"
                  />
                  <img className="vector-3" alt="Vector" src={vector_4} />
                  <img
                    className="vector-4"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-5.svg"
                  />
                  <img
                    className="vector-5"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-6.svg"
                  />
                  <img
                    className="clip-path-group-2"
                    alt="Clip path group"
                    src="https://c.animaapp.com/SHnkkd1L/img/clip-path-group-1@2x.png"
                  />
                  <img
                    className="vector-6"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-7.svg"
                  />
                  <img
                    className="vector-7"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-8.svg"
                  />
                  <img
                    className="vector-8"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-9.svg"
                  />
                  <img
                    className="vector-9"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-10.svg"
                  />
                  <img
                    className="vector-10"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-11.svg"
                  />
                  <img
                    className="vector-11"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-12.svg"
                  />
                  <img
                    className="vector-12"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-13.svg"
                  />
                  <img
                    className="vector-13"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-14.svg"
                  />
                  <img
                    className="vector-14"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-15.svg"
                  />
                  <img
                    className="vector-15"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-16.svg"
                  />
                  <img
                    className="vector-16"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-17.svg"
                  />
                  <img
                    className="vector-17"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-18.svg"
                  />
                  <img
                    className="vector-18"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-20.svg"
                  />
                  <img
                    className="vector-19"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-21.svg"
                  />
                  <img
                    className="vector-20"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-22.svg"
                  />
                  <img
                    className="vector-21"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-23.svg"
                  />
                  <img
                    className="vector-22"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-24.svg"
                  />
                  <img
                    className="vector-23"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-25.svg"
                  />
                  <img
                    className="vector-24"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-26.svg"
                  />
                  <img
                    className="vector-25"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-27.svg"
                  />
                  <img
                    className="vector-26"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-28.svg"
                  />
                  <img
                    className="vector-27"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-29.svg"
                  />
                  <img
                    className="vector-28"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-30.svg"
                  />
                  <img
                    className="vector-29"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-31.svg"
                  />
                  <img
                    className="vector-30"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-32.svg"
                  />
                  <img
                    className="vector-31"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-33.svg"
                  />
                  <img
                    className="vector-32"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-34.svg"
                  />
                  <img
                    className="vector-33"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-35.svg"
                  />
                  <img
                    className="vector-34"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-36.svg"
                  />
                  <img
                    className="vector-35"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-37.svg"
                  />
                  <img
                    className="vector-36"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-38.svg"
                  />
                  <img
                    className="vector-37"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-39.svg"
                  />
                  <img
                    className="vector-38"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-40.svg"
                  />
                  <img
                    className="vector-39"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-41.svg"
                  />
                  <img
                    className="vector-40"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-42.svg"
                  />
                  <img
                    className="vector-41"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-43.svg"
                  />
                  <img
                    className="vector-42"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-44.svg"
                  />
                  <img
                    className="vector-43"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-45.svg"
                  />
                  <img
                    className="vector-44"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-46.svg"
                  />
                  <img
                    className="vector-45"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-47.svg"
                  />
                  <img
                    className="vector-46"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-48.svg"
                  />
                  <img
                    className="vector-47"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-49.svg"
                  />
                  <img
                    className="vector-48"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-50.svg"
                  />
                  <img
                    className="vector-49"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-51.svg"
                  />
                  <img
                    className="vector-50"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-52.svg"
                  />
                  <img
                    className="vector-51"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-53.svg"
                  />
                  <img
                    className="vector-52"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-54.svg"
                  />
                  <img
                    className="vector-53"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-55.svg"
                  />
                  <img
                    className="vector-54"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-56.svg"
                  />
                  <img
                    className="vector-55"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-57.svg"
                  />
                  <img
                    className="vector-56"
                    alt="Vector"
                    src="https://c.animaapp.com/SHnkkd1L/img/vector-58.svg"
                  />
                  <img
                    className="overlap-group"
                    alt="Clip path group"
                    src="https://c.animaapp.com/SHnkkd1L/img/clip-path-group-2.png"
                  />
                </div>
                <img
                  className="vector-57"
                  alt="Vector"
                  src="https://c.animaapp.com/SHnkkd1L/img/vector-19@2x.png"
                />
              </div>
              <div className="div-2">
                <div className="overlap-wrapper">
                  <div className="overlap-2">
                    <div className="div-2">
                      <img
                        className="group-2"
                        alt="Group"
                        src="https://c.animaapp.com/SHnkkd1L/img/group-3379-1@2x.png"
                      />
                    </div>
                    <Header />
                  </div>
                </div>
              </div>
              <LeftContainer />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
